apiVersion: v1
kind: Service
metadata:
  name: service-centos-wordpress
spec:
  ports:
  - port: 8000
    targetPort: 80
    nodePort: 32400
    protocol: TCP
  type: NodePort
  selector:
    app: centos6-wordpress
